### ISSUE TITLE
Autoscroll when at lower or upper bound of the screen?

### ISSUE THREAD

**Issue by palla89** [ShaneQi/SwipeSelectingCollectionView#1]
Hi! First of all: Awesome pod!! Thank you very much :)

Regarding the question: I have a UICollectionView with bigger cells, so the items on the screen are less and the necessity would be to keep the finger pressed all the way down (just as the iPhone Photo App) and the collectionView will scroll and automatically select the remaining items (because the finger will be over the new elements, nothing more) 

Do you think this would be possible? Any hint on how it could be done? Thanks!!!

**Comment by ShaneQi** [comment]
I also wanted to implement the auto-scrolling, just haven't gotten a whole piece of time to do it.

Rough thought: 

In the pan gesture recognizer event handling method (`@objc private func didPanSelectingGestureRecognizerChange(gestureRecognizer: UIPanGestureRecognizer)`), check the position of finger in the whole screen. When the finger is at where you want to auto-scroll, fire auto-scroll, otherwise cancel auto-scroll.

About the auto-scroll part, you could try this post: https://stackoverflow.com/questions/6857975/iphone-how-can-i-programatically-scroll-uiscrollview-from-start-to-end-slowly?rq=1

**Comment by gurpalrajput** [comment]
Hey Thanks For This Awesome Pod, I have slightly different functionality needed in this pod ,

1. When user drag his finger vertically along the sections, so only those cells will be selected,
I don't want to select whole range of cell which comes under beginIndex And EndIndex.
Can You Please Guide Me

**Comment by isnine** [comment]
About autoscroll, i submit Pull request #3   @ShaneQi
