### ISSUE TITLE
How to select Half of UIView in swipe selecting collecion view cell

### ISSUE THREAD

**Issue by Karan-ios** [ShaneQi/SwipeSelectingCollectionView#5]
Hello
I have put two uiview in collectionview cell  upper and bottom view . i seleted full view (upper as well as bottom selected) but i known how to select half view(upper or bottom) please give me any suggestion.
![Screenshot 2020-02-10 at 4 20 29 PM](https://user-images.githubusercontent.com/57385209/74144215-53fe5f80-4c22-11ea-886a-15a58e4998f5.png)

**Comment by ShaneQi** [comment]
Since the selections are tracked and stored by indexPath, there is no way to differentiate if the upper part is selected or the lower part (because they are in the same cell therefore same indexPath).

I'd suggest using 2 cells (for upper and lower part) to represent every cell you are using right now so that they can have different index paths.
